# Generated by Django 4.2 on 2023-04-11 01:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TravelBlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='fechapost',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
