# Generated by Django 4.2 on 2023-04-11 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TravelBlog', '0002_post_fechapost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='categorias',
            field=models.CharField(default='Otros', max_length=50),
        ),
    ]
